# Generated by Django 4.2.6 on 2023-10-25 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ivr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numeroAsociado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=None)),
                ('texto', models.CharField(max_length=300)),
                ('numeroTransferencia', models.CharField(max_length=10)),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
    ]
