# Generated by Django 4.2.6 on 2023-11-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ivr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numeroAsociado', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelf', models.CharField(max_length=10)),
                ('tiempoEspera', models.IntegerField()),
                ('melodia', models.FileField(upload_to='audio/')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=400)),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='Bienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess', models.CharField(max_length=250, null=True)),
                ('musica', models.FileField(null=True, upload_to='bienvenida/')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audios', models.FileField(upload_to='audio/')),
                ('idivr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ivr')),
            ],
        ),
    ]
