# Generated by Django 4.2.6 on 2023-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='melodia',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
