# Generated by Django 4.2.6 on 2023-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienvenida',
            name='mess',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bienvenida',
            name='musica',
            field=models.FileField(blank=True, null=True, upload_to='bienvenida/'),
        ),
    ]
